#!/usr/bin/env python3
"""
Generate seed SQL from algorithm team's data files.
- steel_data_cleaned.csv → energy_realtime_data + steel_energy_dataset
- mpc_results_mean.csv → mpc_realtime_control
"""
import csv
import os
import math

BASE_DIR = "/sessions/admiring-sweet-cray/mnt/挑战杯"
OUT_DIR = os.path.join(BASE_DIR, "AI-challenge")

STEEL_CSV = os.path.join(BASE_DIR, "算法组数据", "steel_data_cleaned.csv")
MPC_CSV  = os.path.join(BASE_DIR, "算法组数据", "mpc_results_mean.csv")

STEEL_SQL_OUT = os.path.join(OUT_DIR, "seed_steel_data.sql")
MPC_SQL_OUT   = os.path.join(OUT_DIR, "seed_mpc_control.sql")

BATCH = 500  # rows per INSERT

def escape_sql(s):
    if s is None or s == '':
        return 'NULL'
    return "'" + str(s).replace("\\", "\\\\").replace("'", "\\'") + "'"

def gen_steel_seed():
    rows = []
    with open(STEEL_CSV, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)

    total = len(rows)
    batches = math.ceil(total / BATCH)

    with open(STEEL_SQL_OUT, 'w', encoding='utf-8') as f:
        f.write("USE challenge_cup_energy;\n\n")
        f.write(f"-- =========================================================\n")
        f.write(f"-- steel_data_cleaned.csv → energy_realtime_data ({total} rows)\n")
        f.write(f"-- Generated by seed generation script\n")
        f.write(f"-- =========================================================\n\n")

        f.write("DELETE FROM energy_realtime_data WHERE source = 'steel_data_cleaned';\n\n")

        for b in range(batches):
            start = b * BATCH
            end = min(start + BATCH, total)
            batch_rows = rows[start:end]

            f.write("INSERT INTO energy_realtime_data (\n")
            f.write("  id, timestamp, raw_timestamp, electricity_consumption, steam_consumption,\n")
            f.write("  carbon_emission_tco2, lagging_reactive_power_kvarh, leading_reactive_power_kvarh,\n")
            f.write("  lagging_power_factor, leading_power_factor, nsm, week_status, day_of_week,\n")
            f.write("  load_type, data_quality, source\n")
            f.write(") VALUES\n")

            vals = []
            for i, row in enumerate(batch_rows):
                idx = start + i
                rid = 7010000000000000000 + idx
                ts_raw = row.get('timestamp', '')
                try:
                    from datetime import datetime
                    dt = datetime.strptime(ts_raw, '%d/%m/%Y %H:%M')
                    ts_fmt = dt.strftime('%Y-%m-%d %H:%M:%S')
                except:
                    ts_fmt = ts_raw

                elec = row.get('elec', 0)
                steam = row.get('steam', 0)
                co2 = row.get('CO2_tCO2_', 0)
                lag_reactive = row.get('Lagging_Current_Reactive_Power_kVarh', 0)
                lead_reactive = row.get('Leading_Current_Reactive_Power_kVarh', 0)
                lag_pf = row.get('Lagging_Current_Power_Factor', 100)
                lead_pf = row.get('Leading_Current_Power_Factor', 100)
                nsm = row.get('NSM', 0)
                week_status = row.get('week_status', '')
                day_of_week = row.get('Day_of_week', '')
                load_type = row.get('load_type', '')

                v = (f"  ({rid}, {escape_sql(ts_fmt)}, {escape_sql(ts_raw)}, "
                     f"{elec}, {steam}, {co2}, {lag_reactive}, {lead_reactive}, "
                     f"{lag_pf}, {lead_pf}, {nsm}, {escape_sql(week_status)}, "
                     f"{escape_sql(day_of_week)}, {escape_sql(load_type)}, "
                     f"'NORMAL', 'steel_data_cleaned')")
                vals.append(v)

            f.write(",\n".join(vals))
            f.write(";\n\n")
            print(f"  energy_realtime_data batch {b+1}/{batches} ({start}-{end})")

        # steel_energy_dataset
        f.write(f"-- =========================================================\n")
        f.write(f"-- steel_data_cleaned.csv → steel_energy_dataset ({total} rows)\n")
        f.write(f"-- =========================================================\n\n")

        f.write("DELETE FROM steel_energy_dataset;\n\n")

        for b in range(batches):
            start = b * BATCH
            end = min(start + BATCH, total)
            batch_rows = rows[start:end]

            f.write("INSERT INTO steel_energy_dataset (\n")
            f.write("  id, timestamp, raw_timestamp, electricity_consumption,\n")
            f.write("  lagging_reactive_power_kvarh, leading_reactive_power_kvarh,\n")
            f.write("  carbon_emission_tco2, lagging_power_factor, leading_power_factor,\n")
            f.write("  nsm, week_status, day_of_week, load_type, steam_consumption, data_quality\n")
            f.write(") VALUES\n")

            vals = []
            for i, row in enumerate(batch_rows):
                idx = start + i
                rid = 7020000000000000000 + idx
                ts_raw = row.get('timestamp', '')
                try:
                    from datetime import datetime
                    dt = datetime.strptime(ts_raw, '%d/%m/%Y %H:%M')
                    ts_fmt = dt.strftime('%Y-%m-%d %H:%M:%S')
                except:
                    ts_fmt = ts_raw

                elec = row.get('elec', 0)
                steam = row.get('steam', 0)
                co2 = row.get('CO2_tCO2_', 0)
                lag_reactive = row.get('Lagging_Current_Reactive_Power_kVarh', 0)
                lead_reactive = row.get('Leading_Current_Reactive_Power_kVarh', 0)
                lag_pf = row.get('Lagging_Current_Power_Factor', 100)
                lead_pf = row.get('Leading_Current_Power_Factor', 100)
                nsm = row.get('NSM', 0)
                week_status = row.get('week_status', '')
                day_of_week = row.get('Day_of_week', '')
                load_type = row.get('load_type', '')

                v = (f"  ({rid}, {escape_sql(ts_fmt)}, {escape_sql(ts_raw)}, "
                     f"{elec}, {lag_reactive}, {lead_reactive}, {co2}, "
                     f"{lag_pf}, {lead_pf}, {nsm}, {escape_sql(week_status)}, "
                     f"{escape_sql(day_of_week)}, {escape_sql(load_type)}, "
                     f"{steam}, 'steel_data_cleaned')")
                vals.append(v)

            f.write(",\n".join(vals))
            f.write(";\n\n")
            print(f"  steel_energy_dataset batch {b+1}/{batches} ({start}-{end})")

    print(f"\nSteel seed SQL → {STEEL_SQL_OUT}")


def gen_mpc_seed():
    rows = []
    with open(MPC_CSV, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)

    total = len(rows)

    with open(MPC_SQL_OUT, 'w', encoding='utf-8') as f:
        f.write("USE challenge_cup_energy;\n\n")
        f.write(f"-- =========================================================\n")
        f.write(f"-- mpc_results_mean.csv → mpc_realtime_control ({total} rows)\n")
        f.write(f"-- Generated by seed generation script\n")
        f.write(f"-- =========================================================\n\n")

        f.write("-- 1. MPC 调控任务记录\n")
        f.write("""INSERT INTO algorithm_task (
  id, task_type, status, progress, result_id, message, retry_count,
  algorithm_name, algorithm_version, result_file_name, algorithm_response_json,
  start_time, finish_time, deleted, remark
)
VALUES (
  5000000000000000002,
  'REALTIME_MPC',
  'SUCCESS',
  100,
  5000000000000000201,
  'mpc_results_mean.csv 导入成功',
  0,
  'MPC_REALTIME_CONTROL',
  'v1.0',
  'mpc_results_mean.csv',
  '{"description":"2-hour MPC rolling optimization results, 1-min granularity, 120 time steps"}',
  '2026-07-17 00:01:00',
  '2026-07-17 02:00:01',
  0,
  '算法组 mpc_results_mean.csv'
)
ON DUPLICATE KEY UPDATE
  status = VALUES(status),
  progress = VALUES(progress),
  result_id = VALUES(result_id),
  message = VALUES(message),
  algorithm_response_json = VALUES(algorithm_response_json),
  finish_time = VALUES(finish_time),
  deleted = 0,
  remark = VALUES(remark);
""")

        f.write("\nDELETE FROM mpc_realtime_control WHERE source_file_name = 'mpc_results_mean.csv';\n\n")
        f.write(f"-- 2. {total} 条 MPC 调控明细（1分钟粒度，2小时窗口）\n")

        batches = math.ceil(total / BATCH)
        for b in range(batches):
            start = b * BATCH
            end = min(start + BATCH, total)
            batch_rows = rows[start:end]

            f.write("INSERT INTO mpc_realtime_control (\n")
            f.write("  id, task_id, control_date, control_time, raw_timestamp,\n")
            f.write("  boiler_load_mw, turbine_output_mw, grid_purchase_kwh, power_factor_target,\n")
            f.write("  elec_next_5min_kwh, steam_next_5min_t, source_file_name, raw_json\n")
            f.write(") VALUES\n")

            vals = []
            for i, row in enumerate(batch_rows):
                idx = start + i
                rid = 5000000000000000200 + idx
                time_str = row.get('Time', '00:00:00')
                elec_actual = float(row.get('Elec_Actual', 0))
                elec_plan = float(row.get('Elec_Plan', 0))
                steam_actual = float(row.get('Steam_Actual', 0))
                boiler_mw = float(row.get('Boiler_MW', 0))
                turbine_mw = float(row.get('Turbine_MW', 0))
                grid_kwh = float(row.get('Grid_kWh', 0))
                elec_error = float(row.get('Elec_Error', 0))

                raw_json = (
                    '{"Time":"' + time_str + '",'
                    '"Elec_Actual":' + str(elec_actual) + ','
                    '"Elec_Plan":' + str(elec_plan) + ','
                    '"Steam_Actual":' + str(steam_actual) + ','
                    '"Boiler_MW":' + str(boiler_mw) + ','
                    '"Turbine_MW":' + str(turbine_mw) + ','
                    '"Grid_kWh":' + str(grid_kwh) + ','
                    '"Elec_Error":' + str(elec_error) + '}'
                )

                v = (f"  ({rid}, 5000000000000000002, '2026-07-17', {escape_sql(time_str)}, "
                     f"{escape_sql(time_str)}, {boiler_mw}, {turbine_mw}, {grid_kwh}, "
                     f"0.950000, {elec_actual}, {steam_actual}, "
                     f"'mpc_results_mean.csv', {escape_sql(raw_json)})")
                vals.append(v)

            f.write(",\n".join(vals))
            f.write(";\n\n")
            print(f"  mpc_realtime_control batch {b+1}/{batches} ({start}-{end})")

    print(f"\nMPC seed SQL → {MPC_SQL_OUT}")


if __name__ == '__main__':
    print("Generating steel data seed SQL...")
    gen_steel_seed()
    print("\nGenerating MPC control seed SQL...")
    gen_mpc_seed()
    print("\nDone!")
